### ISSUE TITLE
Compress can not handle blocks larger than 1.25 Mib

### ISSUE THREAD

**Issue by mrietveld** [samtools/htscodecs#128] opened 2024-11-08 10:35 UTC
In using the the RANS codec here (THANK YOU!), I've noticed that `rans_compress_to_4x16` dumps/does not complete on blocks of input larger than 1.25 * 2^20 (1 Mib). 

If this is not something that you plan to support, or are interested in supporting, please feel free to close the issue. 

Otherwise, if this is a valid bug, I can add a short test case very easily. Thanks! 

I'm not completely sure which RANS variant (order, pack, RLE, stripe) fails, but when I looked into it, it seemed like it affected several of them. A test case will of course clarify this.

**Comment by jkbonfield** [comment] 2024-11-12 10:08
I cannot reproduce this using `./tests/rans4x16pr`.  I've tried:

```
for c in 0x0000 0x0101 0x0202 0x0404;do echo === $c ===;./tests/rans4x16pr -c $c -o196 -t -b `expr 10 "*" 1024 "*" 1024` ~/scratch/data/enwik8;done
```

This tests scalar, SSE4, AVX2 and AVX512 implementations.  I've also done it with order-0, order-1, order-4 (SIMD) and order-5 (SIMD) as well.  There's nothing obvious in there that would limit this to 1MiB blocks.  It's possible once we get close to 2GiB we may be overflowing things with various bits of code, but that's extreme and not what the library was designed for.   It's generally much faster to serialise smaller blocks as they fit in the cache.

Can you provide a concrete example of it failing please?

**Comment by jkbonfield** [comment] 2024-12-12 11:56
Closing as no reply and cannot reproduce.

**Closed by jkbonfield** 2024-12-12 11:56 UTC

**Comment by mrietveld** [comment] 2024-12-19 14:03
Apologies for the late reply, I'll submit a pull request to htscodecs with a test example in January. 

BTW, if you have the chance to answer the following (here or there), I'm very curious: 
https://stackoverflow.com/questions/79294520/what-does-memory-aligning-a-function-to-32-do

The work you've done on CRAM and Samtoolks in general is both groundbreaking and fantastic. IMHO, it's unfortunate that many of your innovations and discoveries are buried in the code (trials, columnization, thread pool, etc.).

**Comment by mrietveld** [comment] 2024-12-20 09:40
Apologies, a test case on v1.6.1 showed that this issue is with my code. I forked htscodecs and modified it to not malloc memory internally -- and apparently made a mistake there. My apologies for not checking this more thoroughly first! 

I only meant to compliment and thank you in my third paragraph, apologies if it came across otherwise! 

Again, apologies and thanks again for your time -- and a merry christmas and happy new year.

**Comment by jkbonfield** [comment] 2025-01-06 11:58
Thanks for verify the cause of this issue and self closing.

Regarding the function alignment, it's one of several speed optimisation that can merged together.  I may still have the explicit commits separated showing this.  Basically there are a number of things like branch prediction that only have so many counters per so many bytes.  Eg (I'm making these up as I forget the details) say 2 branch prediction counters per 8 bytes of instructions.  If we have a function that does lots of if-then-else-if-then-... type code then the efficiency of the prediction can be affected by the memory addresses, and in turn changing one function earlier can shuffle subsequent addresses up or down and alter the speed of that code.

This function was experimentally observed to be one where performance was variable and affected by memory addresses.   It may not be branch prediction, but something like that which impacted performance.  The alignment isn't critical, and almost certainly is CPU specific, but it's now stable and consistent performance (hopefully locked into the "good performance" side of it).
